packages:
  # the root package.json
  - '.'
  # the docs
  - 'docs'
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - '!packages/**/dist'
  # - '!packages/backend'
  # all packages in subdirs of packages/ and components/
  - 'apps/**'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
